version: '3'

services:

  coppelia:
    container_name: ros2coppelia
    image: ros_coppelia
    build:
      context: .
      dockerfile: ./docker/dockerfile_ros_coppelia
    network_mode: host
    userns_mode: host
    ipc: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./coppelia/:/coppelia/:rw
      - ./ros2_ws:/ros/ros2_ws/:rw

  rviz:
    container_name: ros2rviz
    image: ros_rviz
    build:
      context: .
      dockerfile: ./docker/dockerfile_ros_rviz
    network_mode: host
    userns_mode: host
    ipc: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./coppelia/:/rviz/coppelia/:rw
      - ./ros2_ws:/ros/ros2_ws/:rw
      #- ./rosbot_pro.rviz:/root/.rviz2/default.rviz
      #- RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  nav2:
    container_name: ros2nav2
    image: ros_nav
    build: 
      context: .
      dockerfile: ./docker/dockerfile_ros_nav
    network_mode: host
    userns_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/ros/ros2_ws/:rw
      - ./nav2:/nav2_config:ro
    command: ros2 launch nav2_bringup navigation_launch.py params_file:=/nav2_config/nav2_costmap2d_params.yaml
  
  slam:
    container_name: ros2slam
    image: ros_nav
    build: 
      context: .
      dockerfile: ./docker/dockerfile_ros_nav
    network_mode: host
    userns_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/ros/ros2_ws/:rw
      - ./nav2:/nav2_config:ro
    command: ros2 launch slam_toolbox online_async_launch.py slam_params_file:=/nav2_config/nav2_costmap2d_params.yaml