


pkgcreate:
	@scripts/create_pkg.sh $(PKG_NAME)

wsbuild:
	@scripts/ws.sh build

wssource:
	@scripts/ws.sh source

wsclean:
	@rm -rf build install log


help:
	@echo "Options: pkgcreate PKG_NAME - wsbuild - wssource - wsclean"