FROM osrf/ros:humble-desktop

SHELL [ "/bin/bash", "-c" ]

ARG ROS_DISTRO=humble
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        ros-$ROS_DISTRO-rmw-fastrtps-cpp \
        ros-$ROS_DISTRO-rviz2 \
        ros-$ROS_DISTRO-rviz-common \
        ros-$ROS_DISTRO-rviz-default-plugins \
        ros-$ROS_DISTRO-rviz-visual-tools \
        ros-$ROS_DISTRO-rviz-rendering \
        ros-$ROS_DISTRO-navigation2 \
        ros-$ROS_DISTRO-nav2-bringup \
        ros-$ROS_DISTRO-nav2-rviz-plugins \
        ros-$ROS_DISTRO-joint-state-publisher-gui && \ 
        ros-$ROS_DISTRO-xacro && \
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ros/ros2_ws
COPY docker/script_rviz.sh /

ENTRYPOINT [ "/ros_entrypoint.sh" ]
CMD [ "/script_rviz.sh" ]