FROM osrf/ros:humble-desktop

SHELL [ "/bin/bash", "-c" ]

ARG ROS_DISTRO=humble
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        ros-$ROS_DISTRO-navigation2 \
        ros-$ROS_DISTRO-nav2-bringup \
        ros-$ROS_DISTRO-slam-toolbox && \ 
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ros/ros2_ws
COPY docker/script_slam.sh /

ENTRYPOINT [ "/ros_entrypoint.sh" ]
CMD [ "bash" ]