FROM osrf/ros:humble-desktop


ARG COPPELIA_VERSION=CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04
ARG COPPELIA_FILENAME=$COPPELIA_VERSION.tar.xz

ARG DEBIAN_FRONTEND=noninteractive


RUN apt-get update -q && \
    apt-get install -y --no-install-recommends \
        vim tar xz-utils \
        libx11-6 libxcb1 libxau6 libgl1-mesa-dev \
        xvfb dbus-x11 x11-utils libxkbcommon-x11-0 \
        libavcodec-dev libavformat-dev libswscale-dev
RUN apt-get install -y wget && \
        wget https://www.coppeliarobotics.com/files/$COPPELIA_FILENAME -P /opt && \
    apt-get autoclean -y && apt-get autoremove -y && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN tar -xf /opt/$COPPELIA_FILENAME -C /opt && \
    rm /opt/$COPPELIA_FILENAME

ENV COPPELIASIM_ROOT_DIR=/opt/$COPPELIA_VERSION
ENV LD_LIBRARY_PATH=$COPPELIASIM_ROOT_DIR:$LD_LIBRARY_PATH
ENV PATH=$COPPELIASIM_ROOT_DIR:$PATH

RUN echo "#!/bin/bash" > run_coppelia.sh && \
    echo "source /opt/ros/humble/setup.bash" >> run_coppelia.sh && \
    echo "coppeliaSim.sh" >> run_coppelia.sh && \
    chmod +x run_coppelia.sh

ENTRYPOINT [ "/bin/bash", "-c" ]
CMD [ "./run_coppelia.sh" ]